version: "3.7"

services:
  php7.1:
    build: .docker/php7.1
    container_name: php7.1
    volumes:
      - .:/docker:rw
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=php-dev
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_host=172.17.0.1 remote_port=9001"

  php7.2:
    build: .docker/php7.2
    container_name: php7.2
    volumes:
      - .:/docker:rw
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=php-dev
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_host=172.17.0.1 remote_port=9001"

  php7.3:
    build: .docker/php7.3
    container_name: php7.3
    volumes:
      - .:/docker:rw
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=php-dev
      - XDEBUG_CONFIG="idekey=PHPSTORM remote_host=172.17.0.1 remote_port=9001"