version: "3.4"
services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: integration_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: changeme
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: "2s" # Interval between health checks.
      timeout: "2s" # Timeout for each health checking.
      retries: 10 # Hou many times retries.
      start_period: "2s"
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
